spring.application.name=SerbianElection2026
management.endpoints.web.exposure.include=health

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/serbian_elections}
spring.datasource.username=${DATABASE_USERNAME:serbian_elections}
spring.datasource.password=${DATABASE_PASSWORD:serbian_elections}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
